using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DbfManager.DbfModel
{
	public class apbal {
		public string supcod { get; set;}
		public double begbal { get; set;}
		public double hp1 { get; set;}
		public double hp2 { get; set;}
		public double hp3 { get; set;}
		public double hp4 { get; set;}
		public double hp5 { get; set;}
		public double hp6 { get; set;}
		public double hp7 { get; set;}
		public double hp8 { get; set;}
		public double hp9 { get; set;}
		public double hp10 { get; set;}
		public double hp11 { get; set;}
		public double hp12 { get; set;}
		public double hp1ny { get; set;}
		public double hp2ny { get; set;}
		public double hp3ny { get; set;}
		public double hp4ny { get; set;}
		public double hp5ny { get; set;}
		public double hp6ny { get; set;}
		public double hp7ny { get; set;}
		public double hp8ny { get; set;}
		public double hp9ny { get; set;}
		public double hp10ny { get; set;}
		public double hp11ny { get; set;}
		public double hp12ny { get; set;}
		public double rr1 { get; set;}
		public double rr2 { get; set;}
		public double rr3 { get; set;}
		public double rr4 { get; set;}
		public double rr5 { get; set;}
		public double rr6 { get; set;}
		public double rr7 { get; set;}
		public double rr8 { get; set;}
		public double rr9 { get; set;}
		public double rr10 { get; set;}
		public double rr11 { get; set;}
		public double rr12 { get; set;}
		public double rr1ny { get; set;}
		public double rr2ny { get; set;}
		public double rr3ny { get; set;}
		public double rr4ny { get; set;}
		public double rr5ny { get; set;}
		public double rr6ny { get; set;}
		public double rr7ny { get; set;}
		public double rr8ny { get; set;}
		public double rr9ny { get; set;}
		public double rr10ny { get; set;}
		public double rr11ny { get; set;}
		public double rr12ny { get; set;}
		public double cp1 { get; set;}
		public double cp2 { get; set;}
		public double cp3 { get; set;}
		public double cp4 { get; set;}
		public double cp5 { get; set;}
		public double cp6 { get; set;}
		public double cp7 { get; set;}
		public double cp8 { get; set;}
		public double cp9 { get; set;}
		public double cp10 { get; set;}
		public double cp11 { get; set;}
		public double cp12 { get; set;}
		public double cp1ny { get; set;}
		public double cp2ny { get; set;}
		public double cp3ny { get; set;}
		public double cp4ny { get; set;}
		public double cp5ny { get; set;}
		public double cp6ny { get; set;}
		public double cp7ny { get; set;}
		public double cp8ny { get; set;}
		public double cp9ny { get; set;}
		public double cp10ny { get; set;}
		public double cp11ny { get; set;}
		public double cp12ny { get; set;}
		public double gr1 { get; set;}
		public double gr2 { get; set;}
		public double gr3 { get; set;}
		public double gr4 { get; set;}
		public double gr5 { get; set;}
		public double gr6 { get; set;}
		public double gr7 { get; set;}
		public double gr8 { get; set;}
		public double gr9 { get; set;}
		public double gr10 { get; set;}
		public double gr11 { get; set;}
		public double gr12 { get; set;}
		public double gr1ny { get; set;}
		public double gr2ny { get; set;}
		public double gr3ny { get; set;}
		public double gr4ny { get; set;}
		public double gr5ny { get; set;}
		public double gr6ny { get; set;}
		public double gr7ny { get; set;}
		public double gr8ny { get; set;}
		public double gr9ny { get; set;}
		public double gr10ny { get; set;}
		public double gr11ny { get; set;}
		public double gr12ny { get; set;}
		public double ps1 { get; set;}
		public double ps2 { get; set;}
		public double ps3 { get; set;}
		public double ps4 { get; set;}
		public double ps5 { get; set;}
		public double ps6 { get; set;}
		public double ps7 { get; set;}
		public double ps8 { get; set;}
		public double ps9 { get; set;}
		public double ps10 { get; set;}
		public double ps11 { get; set;}
		public double ps12 { get; set;}
		public double ps1ny { get; set;}
		public double ps2ny { get; set;}
		public double ps3ny { get; set;}
		public double ps4ny { get; set;}
		public double ps5ny { get; set;}
		public double ps6ny { get; set;}
		public double ps7ny { get; set;}
		public double ps8ny { get; set;}
		public double ps9ny { get; set;}
		public double ps10ny { get; set;}
		public double ps11ny { get; set;}
		public double ps12ny { get; set;}
	}
}
