using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DbfManager.DbfModel
{
	public class arbal {
		public string cuscod { get; set;}
		public double begbal { get; set;}
		public double hs1 { get; set;}
		public double hs2 { get; set;}
		public double hs3 { get; set;}
		public double hs4 { get; set;}
		public double hs5 { get; set;}
		public double hs6 { get; set;}
		public double hs7 { get; set;}
		public double hs8 { get; set;}
		public double hs9 { get; set;}
		public double hs10 { get; set;}
		public double hs11 { get; set;}
		public double hs12 { get; set;}
		public double hs1ny { get; set;}
		public double hs2ny { get; set;}
		public double hs3ny { get; set;}
		public double hs4ny { get; set;}
		public double hs5ny { get; set;}
		public double hs6ny { get; set;}
		public double hs7ny { get; set;}
		public double hs8ny { get; set;}
		public double hs9ny { get; set;}
		public double hs10ny { get; set;}
		public double hs11ny { get; set;}
		public double hs12ny { get; set;}
		public double iv1 { get; set;}
		public double iv2 { get; set;}
		public double iv3 { get; set;}
		public double iv4 { get; set;}
		public double iv5 { get; set;}
		public double iv6 { get; set;}
		public double iv7 { get; set;}
		public double iv8 { get; set;}
		public double iv9 { get; set;}
		public double iv10 { get; set;}
		public double iv11 { get; set;}
		public double iv12 { get; set;}
		public double iv1ny { get; set;}
		public double iv2ny { get; set;}
		public double iv3ny { get; set;}
		public double iv4ny { get; set;}
		public double iv5ny { get; set;}
		public double iv6ny { get; set;}
		public double iv7ny { get; set;}
		public double iv8ny { get; set;}
		public double iv9ny { get; set;}
		public double iv10ny { get; set;}
		public double iv11ny { get; set;}
		public double iv12ny { get; set;}
		public double dr1 { get; set;}
		public double dr2 { get; set;}
		public double dr3 { get; set;}
		public double dr4 { get; set;}
		public double dr5 { get; set;}
		public double dr6 { get; set;}
		public double dr7 { get; set;}
		public double dr8 { get; set;}
		public double dr9 { get; set;}
		public double dr10 { get; set;}
		public double dr11 { get; set;}
		public double dr12 { get; set;}
		public double dr1ny { get; set;}
		public double dr2ny { get; set;}
		public double dr3ny { get; set;}
		public double dr4ny { get; set;}
		public double dr5ny { get; set;}
		public double dr6ny { get; set;}
		public double dr7ny { get; set;}
		public double dr8ny { get; set;}
		public double dr9ny { get; set;}
		public double dr10ny { get; set;}
		public double dr11ny { get; set;}
		public double dr12ny { get; set;}
		public double sr1 { get; set;}
		public double sr2 { get; set;}
		public double sr3 { get; set;}
		public double sr4 { get; set;}
		public double sr5 { get; set;}
		public double sr6 { get; set;}
		public double sr7 { get; set;}
		public double sr8 { get; set;}
		public double sr9 { get; set;}
		public double sr10 { get; set;}
		public double sr11 { get; set;}
		public double sr12 { get; set;}
		public double sr1ny { get; set;}
		public double sr2ny { get; set;}
		public double sr3ny { get; set;}
		public double sr4ny { get; set;}
		public double sr5ny { get; set;}
		public double sr6ny { get; set;}
		public double sr7ny { get; set;}
		public double sr8ny { get; set;}
		public double sr9ny { get; set;}
		public double sr10ny { get; set;}
		public double sr11ny { get; set;}
		public double sr12ny { get; set;}
		public double re1 { get; set;}
		public double re2 { get; set;}
		public double re3 { get; set;}
		public double re4 { get; set;}
		public double re5 { get; set;}
		public double re6 { get; set;}
		public double re7 { get; set;}
		public double re8 { get; set;}
		public double re9 { get; set;}
		public double re10 { get; set;}
		public double re11 { get; set;}
		public double re12 { get; set;}
		public double re1ny { get; set;}
		public double re2ny { get; set;}
		public double re3ny { get; set;}
		public double re4ny { get; set;}
		public double re5ny { get; set;}
		public double re6ny { get; set;}
		public double re7ny { get; set;}
		public double re8ny { get; set;}
		public double re9ny { get; set;}
		public double re10ny { get; set;}
		public double re11ny { get; set;}
		public double re12ny { get; set;}
	}
}
