using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DbfManager.DbfModel
{
	public class glrep {
		public string repcod { get; set;}
		public string repnam { get; set;}
		public string status { get; set;}
		public string userid { get; set;}
		public DateTime? chgdat { get; set;}
		public string lincod { get; set;}
		public string head_1 { get; set;}
		public string head_2 { get; set;}
		public string head_3 { get; set;}
		public string head_4 { get; set;}
		public string pict_1 { get; set;}
		public string pict_2 { get; set;}
		public string prnctrl { get; set;}
		public string c1_hd1 { get; set;}
		public string c1_hd2 { get; set;}
		public string c2_hd1 { get; set;}
		public string c2_hd2 { get; set;}
		public string c3_hd1 { get; set;}
		public string c3_hd2 { get; set;}
		public string c4_hd1 { get; set;}
		public string c4_hd2 { get; set;}
		public string c5_hd1 { get; set;}
		public string c5_hd2 { get; set;}
		public string c6_hd1 { get; set;}
		public string c6_hd2 { get; set;}
		public string c7_hd1 { get; set;}
		public string c7_hd2 { get; set;}
		public string c8_hd1 { get; set;}
		public string c8_hd2 { get; set;}
		public string c9_hd1 { get; set;}
		public string c9_hd2 { get; set;}
		public string c10_hd1 { get; set;}
		public string c10_hd2 { get; set;}
		public string c11_hd1 { get; set;}
		public string c11_hd2 { get; set;}
		public string c12_hd1 { get; set;}
		public string c12_hd2 { get; set;}
		public string c13_hd1 { get; set;}
		public string c13_hd2 { get; set;}
		public string c14_hd1 { get; set;}
		public string c14_hd2 { get; set;}
		public string c15_hd1 { get; set;}
		public string c15_hd2 { get; set;}
		public string c16_hd1 { get; set;}
		public string c16_hd2 { get; set;}
		public string c17_hd1 { get; set;}
		public string c17_hd2 { get; set;}
		public string c18_hd1 { get; set;}
		public string c18_hd2 { get; set;}
		public string fld1 { get; set;}
		public string fld2 { get; set;}
		public string fld3 { get; set;}
		public string fld4 { get; set;}
		public string fld5 { get; set;}
		public string fld6 { get; set;}
		public string fld7 { get; set;}
		public string fld8 { get; set;}
		public string fld9 { get; set;}
		public string fld10 { get; set;}
		public string fld11 { get; set;}
		public string fld12 { get; set;}
		public string fld13 { get; set;}
		public string fld14 { get; set;}
		public string fld15 { get; set;}
		public string fld16 { get; set;}
		public string fld17 { get; set;}
		public string fld18 { get; set;}
		public string dep1 { get; set;}
		public string dep2 { get; set;}
		public string dep3 { get; set;}
		public string dep4 { get; set;}
		public string dep5 { get; set;}
		public string dep6 { get; set;}
		public string dep7 { get; set;}
		public string dep8 { get; set;}
		public string dep9 { get; set;}
		public string dep10 { get; set;}
		public string dep11 { get; set;}
		public string dep12 { get; set;}
		public string dep13 { get; set;}
		public string dep14 { get; set;}
		public string dep15 { get; set;}
		public string dep16 { get; set;}
		public string dep17 { get; set;}
		public string dep18 { get; set;}
		public string pcent1 { get; set;}
		public string pcent2 { get; set;}
		public string pcent3 { get; set;}
		public string pcent4 { get; set;}
		public string pcent5 { get; set;}
		public string pcent6 { get; set;}
		public string pcent7 { get; set;}
		public string pcent8 { get; set;}
		public string pcent9 { get; set;}
		public string pcent10 { get; set;}
		public string pcent11 { get; set;}
		public string pcent12 { get; set;}
		public string pcent13 { get; set;}
		public string pcent14 { get; set;}
		public string pcent15 { get; set;}
		public string pcent16 { get; set;}
		public string pcent17 { get; set;}
		public string pcent18 { get; set;}
		public string print1 { get; set;}
		public string print2 { get; set;}
		public string print3 { get; set;}
		public string print4 { get; set;}
		public string print5 { get; set;}
		public string print6 { get; set;}
		public string print7 { get; set;}
		public string print8 { get; set;}
		public string print9 { get; set;}
		public string print10 { get; set;}
		public string print11 { get; set;}
		public string print12 { get; set;}
		public string print13 { get; set;}
		public string print14 { get; set;}
		public string print15 { get; set;}
		public string print16 { get; set;}
		public string print17 { get; set;}
		public string print18 { get; set;}
	}
}
