using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DbfManager.DbfModel
{
	public class isinfo {
		public string thinam { get; set;}
		public string addr01 { get; set;}
		public string addr02 { get; set;}
		public string telnum { get; set;}
		public string engnam { get; set;}
		public string addr01eng { get; set;}
		public string addr02eng { get; set;}
		public string trdreg { get; set;}
		public string taxid { get; set;}
		public string linkgl { get; set;}
		public decimal vatrat { get; set;}
		public string flgvat { get; set;}
		public string seditqu { get; set;}
		public string seditfac { get; set;}
		public string chgsalpr { get; set;}
		public string losesal { get; set;}
		public string st_lt_reop { get; set;}
		public string insertit { get; set;}
		public string cost_enc { get; set;}
		public string pvatprorat { get; set;}
		public decimal pvat_rf { get; set;}
		public decimal pvat_nrf { get; set;}
		public string arprefer { get; set;}
		public string apprefer { get; set;}
		public string stprefer { get; set;}
		public string glprefer { get; set;}
		public string cshpurjnl { get; set;}
		public string crepurjnl { get; set;}
		public string purretjnl { get; set;}
		public string othexpjnl { get; set;}
		public string aprcpjnl { get; set;}
		public string paspcqjnl { get; set;}
		public string cshsaljnl { get; set;}
		public string cresaljnl { get; set;}
		public string salretjnl { get; set;}
		public string othincjnl { get; set;}
		public string arrcpjnl { get; set;}
		public string pasrcqjnl { get; set;}
		public string intissjnl { get; set;}
		public string takadjjnl { get; set;}
		public string cosadjjnl { get; set;}
		public string baddbtjnl { get; set;}
		public string bnkmovjnl { get; set;}
		public string incchqjnl { get; set;}
		public string expchqjnl { get; set;}
		public string aradvjnl { get; set;}
		public string apadvjnl { get; set;}
		public string fadprjnl { get; set;}
		public string ardnjnl { get; set;}
		public string apcnjnl { get; set;}
		public string cosmtd { get; set;}
		public string bnkdep { get; set;}
		public string bnkpaid { get; set;}
		public string paspcqauto { get; set;}
		public string accnum00 { get; set;}
		public string accnum01 { get; set;}
		public string accnum02 { get; set;}
		public string accnum03 { get; set;}
		public string accnum04 { get; set;}
		public string accnum05 { get; set;}
		public string accnum06 { get; set;}
		public string accnum07 { get; set;}
		public string accnum08 { get; set;}
		public string accnum09 { get; set;}
		public string accnum10 { get; set;}
		public string accnum11 { get; set;}
		public string accnum12 { get; set;}
		public string accnum13 { get; set;}
		public string accnum14 { get; set;}
		public string accnum15 { get; set;}
		public string accnum16 { get; set;}
		public string accnum17 { get; set;}
		public string accnum18 { get; set;}
		public string accnum19 { get; set;}
		public string accnum20 { get; set;}
		public string accnum21 { get; set;}
		public string accnum22 { get; set;}
		public string accnum23 { get; set;}
		public string accnum24 { get; set;}
		public string accnum25 { get; set;}
		public string accnum26 { get; set;}
		public string accnum27 { get; set;}
		public string accnum28 { get; set;}
		public string accnum29 { get; set;}
		public string accnum30 { get; set;}
		public string accnum31 { get; set;}
		public string accnum32 { get; set;}
		public string accnum33 { get; set;}
		public string accnum34 { get; set;}
		public string accnum35 { get; set;}
		public string accnum36 { get; set;}
		public string accnum37 { get; set;}
		public string accnum38 { get; set;}
		public string accnum39 { get; set;}
		public string accnum40 { get; set;}
		public string accnum41 { get; set;}
		public string accnum42 { get; set;}
		public string accnum43 { get; set;}
		public string accnum44 { get; set;}
		public string accnum45 { get; set;}
		public string pt_str1 { get; set;}
		public string pt_str1eng { get; set;}
		public string petty1 { get; set;}
		public string pt_str2 { get; set;}
		public string pt_str2eng { get; set;}
		public string petty2 { get; set;}
		public string pt_str3 { get; set;}
		public string pt_str3eng { get; set;}
		public string petty3 { get; set;}
		public string pt_str4 { get; set;}
		public string pt_str4eng { get; set;}
		public string petty4 { get; set;}
		public string pt_str5 { get; set;}
		public string pt_str5eng { get; set;}
		public string petty5 { get; set;}
		public string glpict { get; set;}
		public string stpict { get; set;}
		public string fapict { get; set;}
		public string mainloc { get; set;}
		public string negallow { get; set;}
		public string isperpetua { get; set;}
		public string yearthai { get; set;}
		public string peditqu { get; set;}
		public string peditfac { get; set;}
		public string teditqu { get; set;}
		public string teditfac { get; set;}
		public string e_lpursal { get; set;}
		public decimal ardue1 { get; set;}
		public decimal ardue2 { get; set;}
		public decimal arovr1 { get; set;}
		public decimal arovr2 { get; set;}
		public decimal arovr3 { get; set;}
		public decimal apdue1 { get; set;}
		public decimal apdue2 { get; set;}
		public decimal apovr1 { get; set;}
		public decimal apovr2 { get; set;}
		public decimal apovr3 { get; set;}
		public decimal qrdue1 { get; set;}
		public decimal qrdue2 { get; set;}
		public decimal qrovr1 { get; set;}
		public decimal qrovr2 { get; set;}
		public decimal qrovr3 { get; set;}
		public decimal qpdue1 { get; set;}
		public decimal qpdue2 { get; set;}
		public decimal qpovr1 { get; set;}
		public decimal qpovr2 { get; set;}
		public decimal qpovr3 { get; set;}
		public decimal stage1 { get; set;}
		public decimal stage2 { get; set;}
		public decimal stage3 { get; set;}
		public string glrunning { get; set;}
		public string usedep { get; set;}
		public string cndeduct { get; set;}
		public string dndeduct { get; set;}
		public decimal savscrtime { get; set;}
		public string ed_sstkdes { get; set;}
		public string ed_pstkdes { get; set;}
		public string fadprauto { get; set;}
		public string fadprmonly { get; set;}
		public string dprmethod { get; set;}
		public string online { get; set;}
		public string reserve1 { get; set;}
		public string reserve2 { get; set;}
		public decimal reserve3 { get; set;}
		public string reserve4 { get; set;}
		public string usepacking { get; set;}
		public string reprnauth { get; set;}
		public string abnormexit { get; set;}
		public string ovrcrauth { get; set;}
		public string chkneglev { get; set;}
		public string negauth { get; set;}
		public string whoami { get; set;}
		public double mintaxamt { get; set;}
		public decimal mintaxrat { get; set;}
		public string socialid { get; set;}
		public string povdntid { get; set;}
		public decimal dsimlpri { get; set;}
		public decimal dsimlqty { get; set;}
		public decimal dsimlfac { get; set;}
		public string anyloc { get; set;}
		public string loc_cost { get; set;}
		public string loc_dep { get; set;}
		public string use_cqu { get; set;}
		public string st_dat1 { get; set;}
		public string st_dat1eng { get; set;}
		public string st_dat1use { get; set;}
		public string st_dat2 { get; set;}
		public string st_dat2eng { get; set;}
		public string st_dat2use { get; set;}
		public string st_num1 { get; set;}
		public string st_num1eng { get; set;}
		public string st_num1use { get; set;}
		public string st_str1 { get; set;}
		public string st_str1eng { get; set;}
		public string st_str1use { get; set;}
		public string st_str2 { get; set;}
		public string st_str2eng { get; set;}
		public string st_str2use { get; set;}
		public string st_str3 { get; set;}
		public string st_str3eng { get; set;}
		public string st_str3use { get; set;}
		public string st_str4 { get; set;}
		public string st_str4eng { get; set;}
		public string st_str4use { get; set;}
		public string usebarcod { get; set;}
		public string so_cr_lock { get; set;}
		public string so_logloc { get; set;}
		public double crline_a { get; set;}
		public double crline_b { get; set;}
		public double crline_c { get; set;}
		public double crline_d { get; set;}
		public double crline_e { get; set;}
		public string crline_a_l { get; set;}
		public string crline_b_l { get; set;}
		public string crline_c_l { get; set;}
		public string crline_d_l { get; set;}
		public string crline_e_l { get; set;}
		public string ovrcrallow { get; set;}
		public string usejob { get; set;}
		public string jb_str1 { get; set;}
		public string jb_str1eng { get; set;}
		public string jb_str1use { get; set;}
		public string jb_str2 { get; set;}
		public string jb_str2eng { get; set;}
		public string jb_str2use { get; set;}
		public string jb_str3 { get; set;}
		public string jb_str3eng { get; set;}
		public string jb_str3use { get; set;}
		public string jb_str4 { get; set;}
		public string jb_str4eng { get; set;}
		public string jb_str4use { get; set;}
		public string jb_str5 { get; set;}
		public string jb_str5eng { get; set;}
		public string jb_str5use { get; set;}
		public decimal postacc { get; set;}
		public string sharefile { get; set;}
		public string srv_vattyp { get; set;}
		public string reprn_lev { get; set;}
		public string cancel_lev { get; set;}
		public string delete_lev { get; set;}
		public string approv_met { get; set;}
		public string approv_lev { get; set;}
		public string ovrlin_lev { get; set;}
		public string vat_initem { get; set;}
		public string jbpict { get; set;}
		public string vatreplev { get; set;}
		public DateTime? vatrepbeg { get; set;}
		public decimal orgnum { get; set;}
		public string orgstr { get; set;}
	}
}
